### ISSUE TITLE
Crash when saving (Linux + Qt 5.11)

### ISSUE THREAD

**Issue by eszlari** [opentoonz/opentoonz#2107]
I'm working on a flatpak (https://flatpak.org) for opentoonz. It builds and runs, but when I try to save a scene it crashes (version: git master).

```
[New Thread 0x7fffe2908700 (LWP 26)]
ASSERT: "last < rowCount(parent)" in file itemmodels/qabstractitemmodel.cpp, line 2768

Thread 1 "OpenToonz_1.2" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58
58      }
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58
#1  0x000000313083447a in __GI_abort () at /usr/src/debug/glibc/2.24-r0/git/stdlib/abort.c:89
#2  0x00007ffff0c81a6a in qt_message_fatal (context=..., message=...) at global/qlogging.cpp:1839
#3  0x00007ffff0c826a8 in QMessageLogger::fatal (this=this@entry=0x7fffffffb1c0, msg=msg@entry=0x7ffff0f20238 "ASSERT: \"%s\" in file %s, line %d") at global/qlogging.cpp:877
#4  0x00007ffff0c7b879 in qt_assert (assertion=assertion@entry=0x7ffff0f2e2cb "last < rowCount(parent)", file=file@entry=0x7ffff0f25850 "itemmodels/qabstractitemmodel.cpp", line=line@entry=2768) at global/qglobal.cpp:3180
#5  0x00007ffff0e123f6 in QAbstractItemModel::beginRemoveRows (this=this@entry=0xdba6e0 <DvDirModel::instance()::_instance>, parent=..., first=first@entry=0, last=1) at itemmodels/qabstractitemmodel.cpp:2768
#6  0x000000000094eee9 in DvDirModel::refresh (this=this@entry=0xdba6e0 <DvDirModel::instance()::_instance>, index=...) at /run/build/opentoonz/toonz/sources/toonz/filebrowsermodel.cpp:1285
#7  0x000000000094f00b in DvDirModel::refreshFolder (this=0xdba6e0 <DvDirModel::instance()::_instance>, folderPath=..., i=...) at /run/build/opentoonz/toonz/sources/toonz/filebrowsermodel.cpp:1298
#8  0x000000000094efe3 in DvDirModel::refreshFolder (this=0xdba6e0 <DvDirModel::instance()::_instance>, folderPath=..., i=...) at /run/build/opentoonz/toonz/sources/toonz/filebrowsermodel.cpp:1302
#9  0x000000000094efe3 in DvDirModel::refreshFolder (this=0xdba6e0 <DvDirModel::instance()::_instance>, folderPath=..., i=...) at /run/build/opentoonz/toonz/sources/toonz/filebrowsermodel.cpp:1302
#10 0x000000000071054b in DvDirTreeView::onMonitoredDirectoryChanged (this=0x20fb4a0, dirPath=...) at /run/build/opentoonz/toonz/sources/toonz/dvdirtreeview.cpp:1653
#11 0x00007ffff0e8a553 in QMetaObject::activate (sender=sender@entry=0xdac580 <MyFileSystemWatcher::instance()::_instance>, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffb540)
    at kernel/qobject.cpp:3771
#12 0x00007ffff0e8a91b in QMetaObject::activate (sender=0xdac580 <MyFileSystemWatcher::instance()::_instance>, m=m@entry=0xd85b80 <MyFileSystemWatcher::staticMetaObject>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x7fffffffb540) at kernel/qobject.cpp:3633
#13 0x0000000000926742 in MyFileSystemWatcher::directoryChanged (this=<optimized out>, _t1=...) at /run/build/opentoonz/_build/toonz/moc_dvdirtreeview.cpp:128
#14 0x00007ffff0e8a553 in QMetaObject::activate (sender=sender@entry=0x2102e90, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fffffffb660) at kernel/qobject.cpp:3771
#15 0x00007ffff0e8a91b in QMetaObject::activate (sender=sender@entry=0x2102e90, m=m@entry=0x7ffff1101960 <QFileSystemWatcher::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fffffffb660)
    at kernel/qobject.cpp:3633
#16 0x00007ffff0ddc0a5 in QFileSystemWatcher::directoryChanged (this=this@entry=0x2102e90, _t1=..., _t2=...) at .moc/moc_qfilesystemwatcher.cpp:160
#17 0x00007ffff0ddc4d2 in QFileSystemWatcherPrivate::_q_directoryChanged (this=0x2103050, path=..., removed=<optimized out>) at io/qfilesystemwatcher.cpp:160
#18 0x00007ffff0ddc522 in QFileSystemWatcher::qt_static_metacall (_o=_o@entry=0x2102e90, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=<optimized out>, _a=<optimized out>) at .moc/moc_qfilesystemwatcher.cpp:91
#19 0x00007ffff0e8a553 in QMetaObject::activate (sender=sender@entry=0x21029b0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fffffffb7f0) at kernel/qobject.cpp:3771
#20 0x00007ffff0e8a91b in QMetaObject::activate (sender=sender@entry=0x21029b0, m=m@entry=0x7ffff1101920 <QFileSystemWatcherEngine::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fffffffb7f0)
    at kernel/qobject.cpp:3633
#21 0x00007ffff0ddc11c in QFileSystemWatcherEngine::directoryChanged (this=this@entry=0x21029b0, _t1=..., _t2=<optimized out>, _t2@entry=false) at .moc/moc_qfilesystemwatcher_p.cpp:147
#22 0x00007ffff0e0758a in QInotifyFileSystemWatcherEngine::readFromInotify (this=0x21029b0) at io/qfilesystemwatcher_inotify.cpp:407
#23 0x00007ffff0e0771d in QInotifyFileSystemWatcherEngine::qt_static_metacall (_o=_o@entry=0x21029b0, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=<optimized out>, _a=<optimized out>) at .moc/moc_qfilesystemwatcher_inotify_p.cpp:72
#24 0x00007ffff0e8a553 in QMetaObject::activate (sender=sender@entry=0x21029d8, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffca00) at kernel/qobject.cpp:3771
#25 0x00007ffff0e8a91b in QMetaObject::activate (sender=sender@entry=0x21029d8, m=m@entry=0x7ffff1103be0 <QSocketNotifier::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffca00)
    at kernel/qobject.cpp:3633
#26 0x00007ffff0e96a11 in QSocketNotifier::activated (this=this@entry=0x21029d8, _t1=<optimized out>, _t2=...) at .moc/moc_qsocketnotifier.cpp:136
#27 0x00007ffff0e96e91 in QSocketNotifier::event (this=0x21029d8, e=<optimized out>) at kernel/qsocketnotifier.cpp:266
#28 0x00007ffff1ae400d in QApplicationPrivate::notify_helper (this=this@entry=0xe70240, receiver=receiver@entry=0x21029d8, e=e@entry=0x7fffffffcd70) at kernel/qapplication.cpp:3713
#29 0x00007ffff1aebb9e in QApplication::notify (this=0x7fffffffd480, receiver=0x21029d8, e=0x7fffffffcd70) at kernel/qapplication.cpp:3085
#30 0x00007ffff0e5a1da in QCoreApplication::notifyInternal2 (receiver=0x21029d8, event=event@entry=0x7fffffffcd70) at kernel/qcoreapplication.cpp:1048
#31 0x00007ffff0eb6634 in QCoreApplication::sendEvent (event=0x7fffffffcd70, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#32 socketNotifierSourceDispatch (source=0xe9d430) at kernel/qeventdispatcher_glib.cpp:106
#33 0x00007fffeda551c7 in g_main_dispatch (context=0x7fffcc0016f0) at gmain.c:3234
#34 g_main_context_dispatch (context=context@entry=0x7fffcc0016f0) at gmain.c:3899
#35 0x00007fffeda55430 in g_main_context_iterate (context=context@entry=0x7fffcc0016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3972
#36 0x00007fffeda554dc in g_main_context_iteration (context=0x7fffcc0016f0, may_block=may_block@entry=1) at gmain.c:4033
#37 0x00007ffff0eb5666 in QEventDispatcherGlib::processEvents (this=this@entry=0xeed870, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#38 0x00007fffd5ebbc87 in QPAEventDispatcherGlib::processEvents (this=0xeed870, flags=...) at qeventdispatcher_glib.cpp:69
#39 0x00007ffff0e581f9 in QEventLoop::processEvents (this=this@entry=0x7fffffffcfe0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:136
#40 0x00007ffff0e5863f in QEventLoop::exec (this=this@entry=0x7fffffffcfe0, flags=flags@entry=...) at kernel/qeventloop.cpp:214
#41 0x00007ffff0e62344 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1336
#42 0x00007ffff13e7eac in QGuiApplication::exec () at kernel/qguiapplication.cpp:1750
#43 0x00007ffff1ae3e9f in QApplication::exec () at kernel/qapplication.cpp:2898
#44 0x000000000058748a in main (argc=<optimized out>, argv=<optimized out>) at /run/build/opentoonz/toonz/sources/toonz/main.cpp:666

```

**Comment by eszlari** [comment]
Now I have build opentoonz against different Qt versions:
* 5.9 - No crash.
* 5.10 - No crash.
* 5.11 - It crashes.

**Comment by eszlari** [comment]
I rebuild OpenToonz and now it seems to work. Maybe the last KDE runtime update (Qt 5.11.2) fixed it.
