### ISSUE TITLE
Assertion '__n < this->size()'  failed, when browsing in "Choose folder" dialog : 

### ISSUE THREAD

**Issue by fenugrec** [opentoonz/opentoonz#4442]
### Description

When browsing folders and clicking "Up one level" a few times then selecting a folder, opentoonz crashed .

### Steps to Reproduce

1. Start Opentoonz
2. In the "Create new scene" area, click button with three dots to change `Save In:`location
3. Press "Up one level" a few times
4. In the list on the right, double-click any folder
5. crash

### Expected Behavior

Not crash : )

### Screenshots, Video & Crash Logs

Build is the one from the Arch linux repos.

Starting from the console, I get the following output after the crash:
```
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = FileBrowser::Item; _Alloc = std::allocator<FileBrowser::Item>; std::vector<_Tp, _Alloc>::reference = FileBrowser::Item&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

### OpenToonz Version

1.6

### OpenToonz Version Information

Build date May 4, 2022

### Operating System

Linux

### GPU

AMD

**Comment by TomatDividedBy0** [comment]
Can confirm, have run into the _exact_ same problem.

**Comment by flurick** [comment]
@fenugrec @TomatDividedBy0 looked like theres been some change to the startup window, can you still reproduce this issue?

**Comment by flydiscohuebr** [comment]
Same problem using flatpak version https://github.com/flathub/io.github.OpenToonz/issues/22

**Comment by hfiguiere** [comment]
Accessing any element in an empty container is UB. 

Flatpak build with assertions on, so libstdc++ do catch it.

**Comment by andeon** [comment]
@RodneyBaker I tried to reproduce this with the AppImage and a local build, but I couldn’t get the crash to show up. Since this issue is from 2022, it seems like it was fixed at some point, so we can probably close it.

If it happens again, they can comment here or open a new issue with the crash report.

**Comment by hfiguiere** [comment]
You need to build with `-D_GLIBCXX_ASSERTIONS` to reproduce. It's default on Flatpak, but elsewhere it usually is not.

**Comment by andeon** [comment]
Thanks for the info! I’ll compile with `-D_GLIBCXX_ASSERTIONS` and give it another try.

What I got from gdb:

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fffefa4527e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fffefa288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fffefedf90d in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000555555788f85 in FileBrowser::onSelectedItems(std::set<int, std::less<int>, std::allocator<int> > const&) ()
#7  0x00007ffff3312dbf in ??? () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x0000555555bde7f5 in DvItemViewer::selectedItems(std::set<int, std::less<int>, std::allocator<int> > const&) ()
#9  0x00007ffff3fb0df8 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x0000555555a5662f in DvItemViewerPanel::event(QEvent*) ()
#11 0x00007ffff3f6bd45 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff3f746b0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff32d8118 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff3f72874 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff3fcaa39 in ??? () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff3fcdfbf in ??? () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff3f6bd45 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff32d8118 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff3745a3b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#20 0x00007ffff3717bfc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#21 0x00007fffd8afcd06 in ??? () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#22 0x00007ffff19685c5 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff19c7737 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff1967a63 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff3335279 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff32d6a7b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff418aebb in QDialog::exec() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00005555558aa30e in BrowserPopupController::openPopup(QStringList, bool, QString, QWidget const*) ()
#29 0x00007ffff2bcab72 in DVGui::FileField::browseDirectory() () at /home/test/Downloads/code_toonz/toonz/build/lib/opentoonz/libtoonzqt.so
#30 0x00007ffff3312dbf in ??? () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff4067a62 in ??? () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#32 0x00007ffff40683f5 in QAbstractButton::mousePressEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff3fb0df8 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff3f6bd45 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff3f746b0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff32d8118 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007ffff3f72874 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff3fcaa39 in ??? () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007ffff3fcdfbf in ??? () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007ffff3f6bd45 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff32d8118 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007ffff3745a3b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#43 0x00007ffff3717bfc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#44 0x00007fffd8afcd06 in ??? () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#45 0x00007ffff19685c5 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff19c7737 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff1967a63 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff3335279 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x00007ffff32d6a7b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007ffff32df3e8 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00005555556dd00d in main ()
```
